from tap_kustomer.streams.core_resources import (
    AuditLogsStream,
    BrandsStream,
    BrandsDefaultStream,
    CompaniesStream,
    ConversationsStream,
    CustomersStream,
    KlassesStream,
    MessagesStream,
    NotesStream,
    OutboundAccountsStream,
    SatisfactionStream,
    SchedulesStream,
    SchedulesDefaultStream,
    SpamSendersStream,
)
